### ISSUE TITLE
how to create paytm online script

### ISSUE THREAD

**Issue by karankatiyar** [php-earth/help#1]
sir you know

bro    how to create paytm send money script but html coding only but online site work only no app download neeed

**Comment by petk** [comment]
Hello, @karankatiyar welcome to PHP.earth help and your first question here :tada: 

Firstly, I would suggest learning basics of PHP because you'll understand better how such integrations work. In basics you have multiple options here:
* Integrate a simple button - https://paytm.com/business - that way you won't need server side processing (i.e. PHP at all) - so with use of HTML only.
* or go deeper - `Deep Integration for app/ website` section here: https://paytm.com/business to have more control with the payment steps, functionality, and integration in your existing ecommerce system.

**Comment by karankatiyar** [comment]
bro yeh nhi chahiye mujhe

mujhe paytm pe login karke turant automatically 50 r.s send ho jaye uski scripts chahiye 

plz give me

**Comment by petk** [comment]
@karankatiyar Care to translate this to English also? I'm not sure I understand you what you need and what issue you're facing. I think a "button" integration is a good case to start with this. Check the above links. In case you need further assistance, please provide more information, where exactly you get stuck. Thanks.

**Comment by petk** [comment]
In case you need more help with this let us know. Cheers...
